name: burningbros_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  # Icon
  cupertino_icons: ^1.0.8

  # dio
  dio: ^5.4.0

  # state management:
  flutter_bloc: ^8.1.2

  # comparing dart objects
  equatable: ^2.0.5

  # service locator
  get_it: ^7.6.0

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  path_provider: ^2.0.14

  json_annotation: ^4.8.1

  # logger
  logger: ^2.5.0

  dartz: ^0.10.1

  # Cached Image
  cached_network_image: ^3.4.1

  # Check Connect
  connectivity_plus: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.6.1
  hive_generator: ^2.0.1

dependency_overrides:
    analyzer: ^6.2.0


flutter:

  uses-material-design: true
