name: Build Artifacts on Develop

on:
  push:
    branches: [develop]

jobs:
  build_android_apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Set up .env
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - run: flutter pub get
      - run: flutter clean

      - name: Decode keystore from base64
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
