name: Check Code Quality on PR

on:
  pull_request:
    branches: [main,develop]

jobs:
  check_code:
    name: Check Code Quality on PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool
            android/.gradle
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-

      - run: flutter pub get

      - name: Check formatting
        run: dart format . --set-exit-if-changed || true

      - run: flutter analyze --no-fatal-infos --no-fatal-warnings
      - run: flutter test